<HTML>
<BODY BGCOLOR="white">
<PRE>
<FONT color="green">001</FONT>    package org.junit.rules;<a name="line.1"></a>
<FONT color="green">002</FONT>    <a name="line.2"></a>
<FONT color="green">003</FONT>    import static org.junit.Assert.assertThat;<a name="line.3"></a>
<FONT color="green">004</FONT>    import static org.junit.Assert.assertThrows;<a name="line.4"></a>
<FONT color="green">005</FONT>    <a name="line.5"></a>
<FONT color="green">006</FONT>    import java.util.ArrayList;<a name="line.6"></a>
<FONT color="green">007</FONT>    import java.util.List;<a name="line.7"></a>
<FONT color="green">008</FONT>    import java.util.concurrent.Callable;<a name="line.8"></a>
<FONT color="green">009</FONT>    <a name="line.9"></a>
<FONT color="green">010</FONT>    import org.junit.function.ThrowingRunnable;<a name="line.10"></a>
<FONT color="green">011</FONT>    import org.junit.internal.AssumptionViolatedException;<a name="line.11"></a>
<FONT color="green">012</FONT>    import org.hamcrest.Matcher;<a name="line.12"></a>
<FONT color="green">013</FONT>    import org.junit.runners.model.MultipleFailureException;<a name="line.13"></a>
<FONT color="green">014</FONT>    <a name="line.14"></a>
<FONT color="green">015</FONT>    /**<a name="line.15"></a>
<FONT color="green">016</FONT>     * The ErrorCollector rule allows execution of a test to continue after the<a name="line.16"></a>
<FONT color="green">017</FONT>     * first problem is found (for example, to collect _all_ the incorrect rows in a<a name="line.17"></a>
<FONT color="green">018</FONT>     * table, and report them all at once):<a name="line.18"></a>
<FONT color="green">019</FONT>     *<a name="line.19"></a>
<FONT color="green">020</FONT>     * &lt;pre&gt;<a name="line.20"></a>
<FONT color="green">021</FONT>     * public static class UsesErrorCollectorTwice {<a name="line.21"></a>
<FONT color="green">022</FONT>     *      &amp;#064;Rule<a name="line.22"></a>
<FONT color="green">023</FONT>     *      public ErrorCollector collector= new ErrorCollector();<a name="line.23"></a>
<FONT color="green">024</FONT>     *<a name="line.24"></a>
<FONT color="green">025</FONT>     * &amp;#064;Test<a name="line.25"></a>
<FONT color="green">026</FONT>     * public void example() {<a name="line.26"></a>
<FONT color="green">027</FONT>     *      collector.addError(new Throwable(&amp;quot;first thing went wrong&amp;quot;));<a name="line.27"></a>
<FONT color="green">028</FONT>     *      collector.addError(new Throwable(&amp;quot;second thing went wrong&amp;quot;));<a name="line.28"></a>
<FONT color="green">029</FONT>     *      collector.checkThat(getResult(), not(containsString(&amp;quot;ERROR!&amp;quot;)));<a name="line.29"></a>
<FONT color="green">030</FONT>     *      // all lines will run, and then a combined failure logged at the end.<a name="line.30"></a>
<FONT color="green">031</FONT>     *     }<a name="line.31"></a>
<FONT color="green">032</FONT>     * }<a name="line.32"></a>
<FONT color="green">033</FONT>     * &lt;/pre&gt;<a name="line.33"></a>
<FONT color="green">034</FONT>     *<a name="line.34"></a>
<FONT color="green">035</FONT>     * @since 4.7<a name="line.35"></a>
<FONT color="green">036</FONT>     */<a name="line.36"></a>
<FONT color="green">037</FONT>    public class ErrorCollector extends Verifier {<a name="line.37"></a>
<FONT color="green">038</FONT>        private List&lt;Throwable&gt; errors = new ArrayList&lt;Throwable&gt;();<a name="line.38"></a>
<FONT color="green">039</FONT>    <a name="line.39"></a>
<FONT color="green">040</FONT>        @Override<a name="line.40"></a>
<FONT color="green">041</FONT>        protected void verify() throws Throwable {<a name="line.41"></a>
<FONT color="green">042</FONT>            MultipleFailureException.assertEmpty(errors);<a name="line.42"></a>
<FONT color="green">043</FONT>        }<a name="line.43"></a>
<FONT color="green">044</FONT>    <a name="line.44"></a>
<FONT color="green">045</FONT>        /**<a name="line.45"></a>
<FONT color="green">046</FONT>         * Adds a Throwable to the table.  Execution continues, but the test will fail at the end.<a name="line.46"></a>
<FONT color="green">047</FONT>         */<a name="line.47"></a>
<FONT color="green">048</FONT>        public void addError(Throwable error) {<a name="line.48"></a>
<FONT color="green">049</FONT>            if (error == null) {<a name="line.49"></a>
<FONT color="green">050</FONT>                throw new NullPointerException("Error cannot be null");<a name="line.50"></a>
<FONT color="green">051</FONT>            }<a name="line.51"></a>
<FONT color="green">052</FONT>            if (error instanceof AssumptionViolatedException) {<a name="line.52"></a>
<FONT color="green">053</FONT>                AssertionError e = new AssertionError(error.getMessage());<a name="line.53"></a>
<FONT color="green">054</FONT>                e.initCause(error);<a name="line.54"></a>
<FONT color="green">055</FONT>                errors.add(e);<a name="line.55"></a>
<FONT color="green">056</FONT>            } else {<a name="line.56"></a>
<FONT color="green">057</FONT>                errors.add(error);<a name="line.57"></a>
<FONT color="green">058</FONT>            }<a name="line.58"></a>
<FONT color="green">059</FONT>        }<a name="line.59"></a>
<FONT color="green">060</FONT>    <a name="line.60"></a>
<FONT color="green">061</FONT>        /**<a name="line.61"></a>
<FONT color="green">062</FONT>         * Adds a failure to the table if {@code matcher} does not match {@code value}.<a name="line.62"></a>
<FONT color="green">063</FONT>         * Execution continues, but the test will fail at the end if the match fails.<a name="line.63"></a>
<FONT color="green">064</FONT>         */<a name="line.64"></a>
<FONT color="green">065</FONT>        public &lt;T&gt; void checkThat(final T value, final Matcher&lt;T&gt; matcher) {<a name="line.65"></a>
<FONT color="green">066</FONT>            checkThat("", value, matcher);<a name="line.66"></a>
<FONT color="green">067</FONT>        }<a name="line.67"></a>
<FONT color="green">068</FONT>    <a name="line.68"></a>
<FONT color="green">069</FONT>        /**<a name="line.69"></a>
<FONT color="green">070</FONT>         * Adds a failure with the given {@code reason}<a name="line.70"></a>
<FONT color="green">071</FONT>         * to the table if {@code matcher} does not match {@code value}.<a name="line.71"></a>
<FONT color="green">072</FONT>         * Execution continues, but the test will fail at the end if the match fails.<a name="line.72"></a>
<FONT color="green">073</FONT>         */<a name="line.73"></a>
<FONT color="green">074</FONT>        public &lt;T&gt; void checkThat(final String reason, final T value, final Matcher&lt;T&gt; matcher) {<a name="line.74"></a>
<FONT color="green">075</FONT>            checkSucceeds(new Callable&lt;Object&gt;() {<a name="line.75"></a>
<FONT color="green">076</FONT>                public Object call() throws Exception {<a name="line.76"></a>
<FONT color="green">077</FONT>                    assertThat(reason, value, matcher);<a name="line.77"></a>
<FONT color="green">078</FONT>                    return value;<a name="line.78"></a>
<FONT color="green">079</FONT>                }<a name="line.79"></a>
<FONT color="green">080</FONT>            });<a name="line.80"></a>
<FONT color="green">081</FONT>        }<a name="line.81"></a>
<FONT color="green">082</FONT>    <a name="line.82"></a>
<FONT color="green">083</FONT>        /**<a name="line.83"></a>
<FONT color="green">084</FONT>         * Adds to the table the exception, if any, thrown from {@code callable}.<a name="line.84"></a>
<FONT color="green">085</FONT>         * Execution continues, but the test will fail at the end if<a name="line.85"></a>
<FONT color="green">086</FONT>         * {@code callable} threw an exception.<a name="line.86"></a>
<FONT color="green">087</FONT>         */<a name="line.87"></a>
<FONT color="green">088</FONT>        public &lt;T&gt; T checkSucceeds(Callable&lt;T&gt; callable) {<a name="line.88"></a>
<FONT color="green">089</FONT>            try {<a name="line.89"></a>
<FONT color="green">090</FONT>                return callable.call();<a name="line.90"></a>
<FONT color="green">091</FONT>            } catch (AssumptionViolatedException e) {<a name="line.91"></a>
<FONT color="green">092</FONT>                AssertionError error = new AssertionError("Callable threw AssumptionViolatedException");<a name="line.92"></a>
<FONT color="green">093</FONT>                error.initCause(e);<a name="line.93"></a>
<FONT color="green">094</FONT>                addError(error);<a name="line.94"></a>
<FONT color="green">095</FONT>                return null;<a name="line.95"></a>
<FONT color="green">096</FONT>            } catch (Throwable e) {<a name="line.96"></a>
<FONT color="green">097</FONT>                addError(e);<a name="line.97"></a>
<FONT color="green">098</FONT>                return null;<a name="line.98"></a>
<FONT color="green">099</FONT>            }<a name="line.99"></a>
<FONT color="green">100</FONT>        }<a name="line.100"></a>
<FONT color="green">101</FONT>    <a name="line.101"></a>
<FONT color="green">102</FONT>        /**<a name="line.102"></a>
<FONT color="green">103</FONT>         * Adds a failure to the table if {@code runnable} does not throw an<a name="line.103"></a>
<FONT color="green">104</FONT>         * exception of type {@code expectedThrowable} when executed.<a name="line.104"></a>
<FONT color="green">105</FONT>         * Execution continues, but the test will fail at the end if the runnable<a name="line.105"></a>
<FONT color="green">106</FONT>         * does not throw an exception, or if it throws a different exception.<a name="line.106"></a>
<FONT color="green">107</FONT>         *<a name="line.107"></a>
<FONT color="green">108</FONT>         * @param expectedThrowable the expected type of the exception<a name="line.108"></a>
<FONT color="green">109</FONT>         * @param runnable       a function that is expected to throw an exception when executed<a name="line.109"></a>
<FONT color="green">110</FONT>         * @since 4.13<a name="line.110"></a>
<FONT color="green">111</FONT>         */<a name="line.111"></a>
<FONT color="green">112</FONT>        public void checkThrows(Class&lt;? extends Throwable&gt; expectedThrowable, ThrowingRunnable runnable) {<a name="line.112"></a>
<FONT color="green">113</FONT>            try {<a name="line.113"></a>
<FONT color="green">114</FONT>                assertThrows(expectedThrowable, runnable);<a name="line.114"></a>
<FONT color="green">115</FONT>            } catch (AssertionError e) {<a name="line.115"></a>
<FONT color="green">116</FONT>                addError(e);<a name="line.116"></a>
<FONT color="green">117</FONT>            }<a name="line.117"></a>
<FONT color="green">118</FONT>        }<a name="line.118"></a>
<FONT color="green">119</FONT>    <a name="line.119"></a>
<FONT color="green">120</FONT>    }<a name="line.120"></a>




























































</PRE>
</BODY>
</HTML>
